### ISSUE TITLE
The state class '' of this entity is not supported

### ISSUE THREAD

**Issue by spikeygg** [jdeath/rd200v2#18]
I've been using this integration for a while now and it seems that I get this message in the Developer Tools-->Statistics results after a while:

"The state class '' of this entity is not supported"

![image](https://github.com/jdeath/rd200v2/assets/1015891/82a4c6f2-2719-44bf-8213-be9693e30c23)

It happens on both my units and clicking the "FIX ISSUE" button displays this:
![image](https://github.com/jdeath/rd200v2/assets/1015891/d022c0ef-3a9e-4783-b29e-79905763be6a)

**Comment by jdeath** [comment]
I have not seen that issue. The state class should be measurement. Are you running the latest release?

**Comment by spikeygg** [comment]
Yes, at least I think I am. Mine says version 2.9 is installed. That's the latest I see in the HACS box:
![image](https://github.com/jdeath/rd200v2/assets/1015891/63245d9e-bf69-4fee-ac72-a0a032469d94)

When I look at the entities in the developer tools things it doesn't show any `state_class` detail:
![image](https://github.com/jdeath/rd200v2/assets/1015891/8be9f7ad-8989-4de8-8b91-28cca09ced25)

**Comment by jdeath** [comment]
Try version 3.0. Should be fixed now.

**Comment by spikeygg** [comment]
That's great news! However, I just upgraded and restarted HA and it says this in the logs now:

Logger: homeassistant.setup
Source: setup.py:379
First occurred: 8:17:39 AM (2 occurrences)
Last logged: 8:17:56 AM

Unable to prepare setup for platform rd200_ble.sensor: Platform not found (cannot import name 'BATTERY_ENERGY_DISCHARGED_SENSOR' from 'custom_components.rd200_ble.const' (/config/custom_components/rd200_ble/const.py)).

**Comment by jdeath** [comment]
Opps. I uploaded a sensor.py from another integration! Try version 3.1

**Comment by spikeygg** [comment]
Awesome! Thanks jdeath, that was the trick! I think I'm in business.
