### ISSUE TITLE
My RD200v2 Serial starts with FB

### ISSUE THREAD

**Issue by sachiac** [jdeath/rd200v2#25]
Confirmed working when the proper entry added to manifest.json.  Ordered this RD200v2 last month from Amazon and sticker says it was manufactured Mar 2023.

Cool project!  Thanks!

**Comment by jdeath** [comment]
Glad you like it . Closed with Release 3.5

**Comment by sachiac** [comment]
Sorry! I fat-fingered the title.  The serial is "HB" rather than "FB".  Sorry again for my carelessness.
