### ISSUE TITLE
Support for FR:HB?

### ISSUE THREAD

**Issue by bezmax** [jdeath/rd200v2#27]
Hello. I see that [Readme states that `FR:HB` is supported](https://github.com/jdeath/rd200v2/commit/34aa72707b00ed76f7de457dd6b831e6b213ad03), but the[ code seems to include `FR:FB`](https://github.com/jdeath/rd200v2/commit/c4215a568800912ac740d62514940865fd5cfa32) instead. One of the files is wrong. I am currently trying to setuo `FR:HB` and it's not working. Could you please fix one or the other?

Thanks in advance!

**Comment by bezmax** [comment]
Nvm, noticed that `main` already has this fixed.

**Comment by jdeath** [comment]
Opps. I thought I did a release. I'll do it now
