### ISSUE TITLE
Fresh install - Error occurred loading flow for integration

### ISSUE THREAD

**Issue by Daniel-dev22** [jdeath/rd200v2#37]
I just downloaded the integration, restarted ha, noticed the integration didn't discover automatically and went to add the integration manually and got an error.

Error occurred loading flow for integration rd200_ble: cannot import name 'close_stale_connections_by_address' from 'bleak_retry_connector' (/usr/local/lib/python3.11/site-packages/bleak_retry_connector/__init__.py)

**Comment by jdeath** [comment]
You need to update to homeassistant 2024.1.x or revert back to version 4.1
