### ISSUE TITLE
Question regarding the pulse counter

### ISSUE THREAD

**Issue by jonathan-schmieg** [jdeath/rd200v2#38]
Hello,

sorry to create an issue here - my question is not related to this integration but more about the radoneye rd200 itself.
I noticed that I have spikes both in the radon graph over time and especially in the pulse counter graph.
Here's a picture of the pulses:
![2024-01-31_17-25](https://github.com/jdeath/rd200v2/assets/44640302/381d444a-8c6a-435e-a648-de67367c5f58)
And here's one of the overall radon graph:
![2024-01-31_17-26](https://github.com/jdeath/rd200v2/assets/44640302/d4fbc598-e10a-44c0-b9ab-ae7b75195265)
I would be very grateful if someone could let me know whether their graphs show similar spikes or if my device might be broken.
I know that radioactive decay is random but sometimes I have 2 decays in 10m and in the next 10m cycle it's 17. That feels a bit odd.

Thanks,
Jonathan

**Comment by farlight1** [comment]
Hi Jonathan,

It's normal to see spikes in "C pulse counter last", this value is an absolute count of the last 10 min, but the RD200 firmware does its maths with the behaviour of the pulses to show a coherent radon value, so it can go up or down indistintly from the Bqs processed by the firmware.
Pulses are a kind of a RAW data.

for example, this is a C pulse last graph of mine:
![imagen](https://github.com/user-attachments/assets/dbabb981-7705-4a57-a811-44ae0d61a915)
