### ISSUE TITLE
Recent RD200 device not discovered

### ISSUE THREAD

**Issue by genm00** [jdeath/rd200v2#41]
Hi,
i bought a RD200 device recently and it was not discovered using a esp_home bt-proxy (automatically aswell as manual in homeassistant).
Sticker on the box starting with "HG04" - added manually to config_flow.py, restarted HA and it was happily recognized.
Guess its safe to add?

If you want me to test something, shout!

**Comment by jdeath** [comment]
I made the change in https://github.com/jdeath/rd200v2/releases/tag/4.5 . Reopen issue if does not work.
