### ISSUE TITLE
HH serial number

### ISSUE THREAD

**Issue by npinter** [jdeath/rd200v2#43]
Ordered two RD200, both have a HH serial number. Added to `config_flow.py` and both were found. Wouldn't it be better to check the serial number if it contains `FR:` , then fetch the model number and check if its a `RD200v2` instead of checking the first two chars of the serial number?

Thanks for providing this nice integration :)

**Comment by jdeath** [comment]
Probably would be easier, but I am worried it will find extra devices on the network. I'll add HH
